### PR TITLE
Feature#15 Profile screen style

### PR DESCRIPTION
**Pull request by cortezroberto**
# Description
 - We've created styled components to the 'Profile' screen, this screen will allow the user to update personal information like name, password and profile picture.
 - Name and Password input to allow user update it's information.
 - Name data will be retrieved from firebase, Password data won't, for security purposes, but the user will be allowed to enter a new password and update it.
 - We've implemented the styled component button that we already created before.
- We have created a link to "log out" that is in the upper right corner of the screen. This will allow the user to log out successfully and will be redirected to the 'log in' screen. 

 Examples:
 - The user wants to change it's username/password.
 - The user wants to change it's profile picture.
 - The user wants to log out.
 
# Notes
 - _signInWithNameEmailAndPassword_ schema and any other functions will be **changed/added** on a different issue, this issue is only for style purposes.
  
  ## Screenshots 
Screenshot_20210823-112539

### CODE REVIEW

**Comment by cortezroberto** [comment]
image

Codacy está marcando ese error, por el momento sí es necesario tener esos props para validación por lo que ignoraremos ese issue, despues se modificará con las validaciones respectivas.

**Review by jkzasori — APPROVED** [review]
It's okay

**Comment by jkzasori** [comment]
> image
> 
> Codacy está marcando ese error, por el momento sí es necesario tener esos props para validación por lo que ignoraremos ese issue, despues se modificará con las validaciones respectivas.

**Comment by jkzasori** [comment]
> image
> 
> Codacy está marcando ese error, por el momento sí es necesario tener esos props para validación por lo que ignoraremos ese issue, despues se modificará con las validaciones respectivas.

Okay.

**Review by yovanha — APPROVED** [review]

**Pull request merged**
